<?php

namespace Database\Seeders;

use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;
use Carbon\Carbon;

class VehicleBrandSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $now = Carbon::now();

        $cars = [
            [
                'id' => 1,
                'name' => 'Toyota Agya',
                'merk' => 'Toyota',
                'model' => 'Agya',
                'remarks' => null,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'id' => 2,
                'name' => 'Toyota Calya',
                'merk' => 'Toyota',
                'model' => 'Calya',
                'remarks' => null,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'id' => 3,
                'name' => 'Toyota Avanza',
                'merk' => 'Toyota',
                'model' => 'Avanza',
                'remarks' => null,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'id' => 4,
                'name' => 'Toyota Veloz',
                'merk' => 'Toyota',
                'model' => 'Veloz',
                'remarks' => null,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'id' => 5,
                'name' => 'Toyota Rush',
                'merk' => 'Toyota',
                'model' => 'Rush',
                'remarks' => null,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'id' => 6,
                'name' => 'Toyota Raize',
                'merk' => 'Toyota',
                'model' => 'Raize',
                'remarks' => null,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'id' => 7,
                'name' => 'Daihatsu Ayla',
                'merk' => 'Daihatsu',
                'model' => 'Ayla',
                'remarks' => null,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'id' => 8,
                'name' => 'Daihatsu Sigra',
                'merk' => 'Daihatsu',
                'model' => 'Sigra',
                'remarks' => null,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'id' => 9,
                'name' => 'Daihatsu Xenia',
                'merk' => 'Daihatsu',
                'model' => 'Xenia',
                'remarks' => null,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'id' => 10,
                'name' => 'Daihatsu Terios',
                'merk' => 'Daihatsu',
                'model' => 'Terios',
                'remarks' => null,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'id' => 11,
                'name' => 'Daihatsu Rocky',
                'merk' => 'Daihatsu',
                'model' => 'Rocky',
                'remarks' => null,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'id' => 12,
                'name' => 'Daihatsu Sirion',
                'merk' => 'Daihatsu',
                'model' => 'Sirion',
                'remarks' => null,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'id' => 13,
                'name' => 'Daihatsu Luxio',
                'merk' => 'Daihatsu',
                'model' => 'Luxio',
                'remarks' => null,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'id' => 14,
                'name' => 'Daihatsu GranMax',
                'merk' => 'Daihatsu',
                'model' => 'GranMax',
                'remarks' => null,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'id' => 15,
                'name' => 'Honda Brio',
                'merk' => 'Honda',
                'model' => 'Brio',
                'remarks' => null,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'id' => 16,
                'name' => 'Honda Mobilio',
                'merk' => 'Honda',
                'model' => 'Mobilio',
                'remarks' => null,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'id' => 17,
                'name' => 'Honda WR-V',
                'merk' => 'Honda',
                'model' => 'WR-V',
                'remarks' => null,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'id' => 18,
                'name' => 'Suzuki Ertiga',
                'merk' => 'Suzuki',
                'model' => 'Ertiga',
                'remarks' => null,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'id' => 19,
                'name' => 'Suzuki XL7',
                'merk' => 'Suzuki',
                'model' => 'XL7',
                'remarks' => null,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'id' => 20,
                'name' => 'Suzuki Ignis',
                'merk' => 'Suzuki',
                'model' => 'Ignis',
                'remarks' => null,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'id' => 21,
                'name' => 'Suzuki Baleno',
                'merk' => 'Suzuki',
                'model' => 'Baleno',
                'remarks' => null,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'id' => 22,
                'name' => 'Suzuki S-Presso',
                'merk' => 'Suzuki',
                'model' => 'S-Presso',
                'remarks' => null,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'id' => 23,
                'name' => 'Mitsubishi Xpander',
                'merk' => 'Mitsubishi',
                'model' => 'Xpander',
                'remarks' => null,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'id' => 24,
                'name' => 'Wuling Confero',
                'merk' => 'Wuling',
                'model' => 'Confero',
                'remarks' => null,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'id' => 25,
                'name' => 'Wuling Cortez',
                'merk' => 'Wuling',
                'model' => 'Cortez',
                'remarks' => null,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'id' => 26,
                'name' => 'Wuling Almaz',
                'merk' => 'Wuling',
                'model' => 'Almaz',
                'remarks' => null,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'id' => 27,
                'name' => 'Wuling Air EV',
                'merk' => 'Wuling',
                'model' => 'Air EV',
                'remarks' => null,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'id' => 28,
                'name' => 'Hyundai Stargazer',
                'merk' => 'Hyundai',
                'model' => 'Stargazer',
                'remarks' => null,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'id' => 29,
                'name' => 'Hyundai Creta',
                'merk' => 'Hyundai',
                'model' => 'Creta',
                'remarks' => null,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'id' => 30,
                'name' => 'Nissan Magnite',
                'merk' => 'Nissan',
                'model' => 'Magnite',
                'remarks' => null,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'id' => 31,
                'name' => 'Kia Sonet',
                'merk' => 'Kia',
                'model' => 'Sonet',
                'remarks' => null,
                'created_at' => $now,
                'updated_at' => $now,
            ],
        ];


        DB::table('vehicle_brands')->upsert($cars, ['id'], ['name', 'merk', 'model', 'remarks', 'updated_at']);
    }
}
